
# This file is used to configure the Supabase project

# project_id should always be the first line!
project_id = "suvxmnrnldfhfwxvkntv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"

[analytics]
enabled = false

[experimental]
multiservice = false
storageV2 = false
graphql_v1 = false

# Configure the MCP function to not require JWT verification
[functions.mcp]
verify_jwt = false
